sudo: required

services:
    - docker
    
before_install:
    - docker build -t fhsinchy/test-api -f ./api/dev-Dockerfile ./api
    - docker build -t fhsinchy/test-client -f ./client/dev-Dockerfile ./client

script:
    - docker run fhsinchy/test-api npm run test
    - docker run fhsinchy/test-client npm run test:unit