version: "3.8"

services: 
    db:
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: 63eaQB9wtLqmNBpg
            POSTGRES_DB: noteapplication
    nginx:
        build: ./nginx
        ports: 
            - 80:80
        restart: always
    api:
        build: ./api
        command: [ "npm", "run", "dev" ]
        volumes: 
            - /usr/app/node_modules
            - ./api:/usr/app
        environment: 
            - DB_CONNECTION=pg
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_DATABASE=noteapplication
            - DB_PASSWORD=63eaQB9wtLqmNBpg
    client:
        build:
            context: ./client
            dockerfile: dev-Dockerfile
        volumes: 
            - /usr/app/node_modules
            - ./client:/usr/app
        environment: 
            - VUE_APP_API_URL=/api